/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jniprojectcmake_Util */

#ifndef _Included_com_jniprojectcmake_Util
#define _Included_com_jniprojectcmake_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jniprojectcmake_Util
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jniprojectcmake_Util_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
